### ISSUE TITLE
Error: past end:649935989-2097188320 < 650704372

### ISSUE THREAD

**Issue by kyphae** [flumedb/flumedb#32]
On starting Patchbay, I get the following error. No new messages are appearing and most old messages aren't rendering. All messages in the `/gatherings` section just say 'Loading'. No user icons load.

I'm unable to use this feed, I'm resyncing now but will keep this feed for bug fixing purposes, depending on what you guys think.

@mixmix @dominictarr any thoughts? Looks to me like the sequencing is off somehow, though how it happened I've no idea. I've not done anything particularly special.

```
Error: view stream error
    at /shared/Projects/patchbay/node_modules/flumedb/index.js:139:35
    at /shared/Projects/patchbay/node_modules/pull-stream/sinks/drain.js:20:24
    at /shared/Projects/patchbay/node_modules/pull-stream/throughs/async-map.js:28:19
    at /shared/Projects/patchbay/node_modules/pull-cursor/skip.js:12:26
    at /shared/Projects/patchbay/node_modules/pull-cursor/cursor.js:28:28
    at /shared/Projects/patchbay/node_modules/flumelog-offset/inject.js:42:22
    at /shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at Object.read (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:49:14)
  Error: past end:649935989-2097188320 < 650704372
    at Object.read (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:49:17)
    at next (/shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:95:11
    at get (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:92:9)
    at /shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:41:16
    at Array.<anonymous> (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:95:11)
    at /shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:39:16
    at /shared/Projects/patchbay/node_modules/aligned-block-file/file.js:46:13
```

**Comment by dominictarr** [comment]
@KGibb8 when something like this happens, the best thing is to keep a copy of the `~/.ssb/flume/log.offset` file. hmm, oh what it looks like a view pointed to a record that wasn't actually where a record was ment to be. I think if you just rebuild the indexes, it will work. You could probably just rebuild that particular index (but unfortunately I'm not sure which one it is) but I've added the view name to that error message in flumedb@1.0.6

**Comment by mixmix** [comment]
what's the best way to rebuild the indexes at the moment Dominic?
was there a command ... or do you just have to delete each of the indexes by hand carefully?

**Comment by dominictarr** [comment]
hmm, there is a flumedb method, but it's not exposed in ssb (easy PR though)
I just do `rm ~/.ssb/flume/*/* ~/.ssb/flume/*.{json,ht}`
note: `~/.ssb/flume/*/* ` is contents of leveldbs. `~/.ssb/flume/*.{json,ht}` is flumeview-reduce and hashtable. this avoids deleting `log.offset`

**Comment by dominictarr** [comment]
oh best to do that while server is stopped, btw

**Comment by dominictarr** [comment]
that is very prudent @mixmix 
the other option is add https://github.com/flumedb/flumedb#flumedbrebuild-cb to ssb-db
then you wouldn't even need to restart the server.

**Comment by christianbundy** [comment]
FWIW, I think @justinabrahms has a `log.offset` that can reproduce this issue. :tada:

**Comment by justinabrahms** [comment]
I do indeed. Let me know how I can help.

**Comment by christianbundy** [comment]
Related: how does flumedb / flumelog-offset ensure that multiple instances of flumedb aren't writing to the same log at the same time? I'm trying to debug https://github.com/ssbc/patchwork/issues/1192 and I'm unsure how people are getting corrupt logs in the first place.

**Comment by christianbundy** [comment]
I'm concerned about this bug. It's [common on GitHub](https://github.com/search?q=%22past+end%22+user%3Assbc&type=Issues) and I've seen it mentioned on SSB a bunch too. I've spent at least a dozen hours helping people troubleshoot it, and would love some help trying to resolve it. I'll post a brain-dump of what I know so far:

It seems like the views are all instances of flumeview-level, but it could be a red herring.

- links2
- contacts2
- clock
- keys
- last

The `start` value always seems reasonable, but the `end` value is always ridiculous. Here are some sample ranges:

|       start |           end |         max |
|------------:|--------------:|------------:|
| 765 430 172 | 2 784 160 752 | 807 811 345 |
| 649 935 989 | 2 097 188 320 | 650 704 372 |
| 636 332 478 | 2 702 185 763 | 638 495 144 |
|       1 173 |   779 316 470 | 648 890 483 |
| 672 420 546 | 2 374 485 795 | 673 286 541 |
| 680 414 149 | 2 431 614 458 | 680 418 068 |

It's strange that the end is always more than twice the size of the start value, but it isn't a consistent coefficient or anything simple. There are two failure modes I'm most suspicious of:

- **Invalid data written to the flumelog.** The flumelog [format](https://github.com/flumedb/flumelog-offset#format) encodes the length of each item, but when we read the length it seems to be an impossibly huge number. Maybe we're writing it incorrectly.
- **Invalid data written to the flumeview.** The flumeviews keep track of the sequence numbers of various items, maybe those are getting recorded incorrectly? If so, that means we're reading some arbitrary offset and trying to decode it as the length of the item. **I'm leaning toward this, because deleting indexes seems to solve the problem for most people.**

Assuming it's the latter, the `length` value (`end - start`) isn't an integer, it's actually 4 bytes of a random message. Maybe we can test that theory?

```javascript
const readData = (input) => {
  const buffer = Buffer.alloc(4)
  buffer.writeUInt32BE(input)
  return buffer.toString()
}

const lengths = [
  2784160752 - 765430172,
  2097188320 - 649935989,
  2702185763 - 636332478,
   779316470 -      1173,
  2374485795 - 672420546,
  2431614458 - 680414149
]

lengths.map(readData) /* =>
[
  'xSbT',
  'VCQk',
  '{"ke',
  '.sha',
  'esta', 
  'ha25'
]
*/
```
🤯

I recognize `{ "key" }`, bits of `sha256`, part of the word tim**esta**mp, and some base64-encoded data. Looks like an SSB message to me! But why is flumeview-level saving the wrong sequence number to the database?  Investigating now... :male_detective: 

P.S. I know this isn't currently possible, but it would be great if flumelog-offset could look at a sequence number and say "that's not a valid offset, that's the middle of a message". Maybe we can discuss this in the future.

**Comment by christianbundy** [comment]
The way this *should* work:

- Message is appended to FlumeDB
- FlumeDB passes the message to Flumelog-Offset, which returns the message and a sequence number.
  - The sequence number is actually the byte offset of the item in the file, so it goes up like `1`, `483`, `932`, and so on.
- FlumeDB passes the message and sequence number to Flumeview-Level
- Flumeview-Level is **supposed to** make a key:value record with an context-dependent key and the sequence number as the value.
  ```javascript
  {
    key: someKey,
    value: 42
  }
  ```
- It seems that it's encoding the key incorrectly. It's unclear whether it's encoding high or low, but maybe there's a pattern here too. 

The read/write implementations are pretty simple, which is great, and I'm currently pretending that LevelDB is infallible (:sweat_smile:), which doesn't leave me with many options for investigation. One bit that caught my eye was a FlumeDB comment here:

https://github.com/flumedb/flumedb/blob/6008c03ad637607a236180e78f897cf0fea4fbde/index.js#L124

Let's test it! Most of this code is really solid, so it's hard to reproduce a bad `since` state without shooting ourselves in the foot on purpose. Let's do that. What happens if we lie and change the initial view `since` state to some bogus value?

```diff
diff --git a/index.js b/index.js
index f57a16b..b0715dd 100644
--- a/index.js
+++ b/index.js
@@ -65,7 +65,7 @@ module.exports = function (version, map) {
       db = create()
       db.get(META, { keyEncoding: 'utf8' }, function (err, value) {
         if (err) {
-          since.set(-1)
+          since.set(1234)
         } else if (value.version === version) {
           since.set(value.since)
         } else {
@@ -73,7 +73,7 @@ module.exports = function (version, map) {
           outdated = true
           destroy(function () {
             db = create()
-            since.set(-1)
+            since.set(1234)
           })
         }
       })
```

```
Error: view stream error, from:index
    at /home/christianbundy/src/flumeview-level/node_modules/flumedb/index.js:140:35
    at /home/christianbundy/src/flumeview-level/node_modules/pull-cursor/cursor.js:7:24
    at /home/christianbundy/src/flumeview-level/node_modules/pull-looper/index.js:6:5
    at /home/christianbundy/src/flumeview-level/node_modules/pull-looper/node_modules/looper/index.js:11:9
    at /home/christianbundy/src/flumeview-level/node_modules/pull-looper/index.js:11:5
    at next (/home/christianbundy/src/flumeview-level/node_modules/pull-stream/throughs/filter.js:14:9)
    at /home/christianbundy/src/flumeview-level/node_modules/pull-looper/index.js:6:5
  Error: aborted
    at Function.reader.abort (/home/christianbundy/src/flumeview-level/node_modules/pull-write/index.js:67:19)
    at close (/home/christianbundy/src/flumeview-level/index.js:45:16)
    at Object.destroy (/home/christianbundy/src/flumeview-level/index.js:58:7)
    at /home/christianbundy/src/flumeview-level/node_modules/flumedb/index.js:129:16
    at Function.many.once (/home/christianbundy/src/flumeview-level/node_modules/obv/index.js:39:7)
    at build (/home/christianbundy/src/flumeview-level/node_modules/flumedb/index.js:126:19)
    at Function.many.once (/home/christianbundy/src/flumeview-level/node_modules/obv/index.js:39:7)
    at /home/christianbundy/src/flumeview-level/node_modules/flumedb/index.js:141:28
    at /home/christianbundy/src/flumeview-level/node_modules/pull-write/index.js:72:17
    at /home/christianbundy/src/flumeview-level/node_modules/pull-stream/throughs/filter.js:17:11
```

Nice! I added some logs to check the view and log state, and saw this:

```
{ viewState: 1234, logState: 163 }
```

What happens if we change that to `123` instead? It's wrong, but FlumeDB doesn't actually have a way of knowing that it's wrong (because it's still lower than the log state).

```
Error: view stream error, from:index
    at /home/christianbundy/src/flumeview-level/node_modules/flumedb/index.js:140:35
    at /home/christianbundy/src/flumeview-level/node_modules/pull-write/index.js:40:31
    at /home/christianbundy/src/flumeview-level/node_modules/pull-write/index.js:41:13
    at /home/christianbundy/src/flumeview-level/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/src/flumeview-level/node_modules/pull-cursor/skip.js:12:26
    at /home/christianbundy/src/flumeview-level/node_modules/pull-cursor/cursor.js:28:28
    at /home/christianbundy/src/flumeview-level/node_modules/flumelog-offset/inject.js:43:22
    at /home/christianbundy/src/flumeview-level/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at Object.read (/home/christianbundy/src/flumeview-level/node_modules/aligned-block-file/blocks.js:49:14)
  Error: past end:127-577138670 < 245
    at Object.read (/home/christianbundy/src/flumeview-level/node_modules/aligned-block-file/blocks.js:49:17)
    at next (/home/christianbundy/src/flumeview-level/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /home/christianbundy/src/flumeview-level/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /home/christianbundy/src/flumeview-level/node_modules/aligned-block-file/blocks.js:96:11
    at get (/home/christianbundy/src/flumeview-level/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/home/christianbundy/src/flumeview-level/node_modules/aligned-block-file/blocks.js:93:9)
    at /home/christianbundy/src/flumeview-level/node_modules/flumelog-offset/frame/recoverable.js:41:16
    at /home/christianbundy/src/flumeview-level/node_modules/aligned-block-file/blocks.js:96:11
    at get (/home/christianbundy/src/flumeview-level/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/home/christianbundy/src/flumeview-level/node_modules/aligned-block-file/blocks.js:93:9)
```

Reproduced! And we can double-check with the code above:

```javascript
readData(577138670 - 127) // => '"foo'
```

**Summary:** This seems to be a bug that happens when a Flumeview starts with a corrupt state that's lower than the Flumelog's state but not actually a valid sequence number. It might look something like this:

- Log: `0 42 135 790`
- View: `0 42 135 700`

When FlumedDB sees the view claim that its last message had a sequence number of 700, it looks at byte 700 and reads 4 bytes to try to determine the length of the item (so that it can start with the next item). Since these 4 bytes are actually arbitrary message data, they're decoded as some ridiculous number and FlumeDB doesn't know how to proceed.

I'm still unsure about why or how this broken state happens. It doesn't make sense to me that the view could be passed a sequence number that the log isn't aware of. I was thinking that Flumelog-Offset's [recovery](https://github.com/flumedb/flumelog-offset#recovery) might be involved, but the rollback would make the log state higher than the view state. :thinking: 

**Quickfix:** Maybe FlumeDB should get way more aggressive with rebuilding broken views? Currently it just retries the operation until it hits the maximum stack size, but since we know which view is broken we have the option of forcing a rebuild whenever we hit corruption.

**Comment by dominictarr** [comment]
wow, excellent debugging @christianbundy !!!

**Comment by mixmix** [comment]
Awesome sleuthing cb

Fwiw I'm keen for the "rebuild index" method to be exposed for some private
group work we're doing

**Comment by dominictarr** [comment]
how did I not realize until now that @christianbundy's initials are "call back" thanks @mixmix
