### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by mcollina** [flumedb/flumedb#5]
what are your plans on replication? 

The idea should be to replicate the log, and recompute all the views, however this might take a huge amount of time.

**Comment by dominictarr** [comment]
for primary-secondary: this is very easy. regenerating all the views should not be too time consuming, especially since once the logs are in sync.

for primary-primary (subsets): in secure scuttlebutt, we replicate in a higher layer, so that peers end up with different orderings in their logs, and then views are generated on each peer. (also, in ssb, peers may replicate different sets of data, so they obviously end up with different orders and views.

for primary-primary (exact): you could also use raft/paxos so that the log is consistent across multilpe peers. I don't have any plans to implement this my self, but there are quite a few implementations on npm already https://www.npmjs.com/search?q=raft

**Comment by dominictarr** [comment]
oh yeah, it's also possible to replicate a view (I also need this is for secure-scuttlebut) but depends on the implementation of the view. In flumeview-reduce it's particularily easy, though. (just send the current state, and then tail the changes)

**Comment by mcollina** [comment]
Thanks for the detailed discussion, I might give the raft thing a try, or replicate at a higher level as you suggest!
